# Generated by Django 5.2.8 on 2025-11-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='media',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
